POST http://localhost:3000/user/login
content-type: application/json

{
    "username": "ali",
    "password": "ali1234"
}

###

POST http://localhost:3000/project/add?username=manager&password=manager1234
content-type: application/json

{
  "title": "project 4",
  "program_deadline": "2024-09-02",
  "vote_deadline": "2024-11-2"
}

###

POST http://localhost:3000/program/add?username=ali&password=ali1234
content-type: application/json

{
  "project_id": 2,
  "title": "program 2 of ali"
}

###

POST http://localhost:3000/vote/add?username=ahmad&password=ahmad1234
content-type: application/json

{
  "program_id": 3
}

###